### CUSTOMER ENDPOINT
### POST
POST http://localhost:8000/customer HTTP/1.1
content-type: application/json

{
  "customerName": "Minh Vu",
  "contactLastName": "Vu",
  "contactFirstName": "Minh",
  "phone": "123456778",
  "addressLine1": "8672 Luna Brooks",
  "addressLine2": "4446 Doyle Dale",
  "city": "Olympia",
  "state": "North Carolina",
  "postalCode": "GS",
  "country": "Ghana",
  "salesRepEmployeeNumber": "76",
  "creditLimit": "58610"
}

### GET ALL
GET http://localhost:8000/customer?page=1&limit=3 HTTP/1.1

### GET BY ID
GET http://localhost:8000/customer/15 HTTP/1.1

### PUT
PUT http://localhost:8000/customer/15 HTTP/1.1
content-type: application/json

{
  "customerNumber": 11,
  "customerName": "Minh Jackma",
  "contactLastName": "Leonarding",
  "contactFirstName": "Json",
  "phone": "123456778",
  "addressLine1": "8672 Luna Brooks",
  "addressLine2": "4446 Doyle Dale",
  "city": "Olympia",
  "state": "North Carolina",
  "postalCode": "GSDAS",
  "country": "Ghana",
  "salesRepEmployeeNumber": 10,
  "creditLimit": 58610
}

### DELETE
DELETE  http://localhost:8000/customer/15 HTTP/1.1


### EMPLOYEE ENDPOINT
### GET ALL
GET http://localhost:8000/employee?page=1&limit=3 HTTP/1.1

### GET BY ID
GET http://localhost:8000/employee/15 HTTP/1.1

### PUT
PUT http://localhost:8000/employee/15 HTTP/1.1
content-type: application/json

{
  "lastName": "Minh",
  "firstName": "Vu",
  "email": "minh2027@gmail.com",
  "extension": "718y8vl07u",
  "officeCode": "xmwtr523kr",
  "reportsTo": 3,
  "jobTitle": "manager"
}

### POST
POST http://localhost:8000/employee HTTP/1.1
content-type: application/json

{
  "lastName": "Minh",
  "firstName": "Vu",
  "email": "minh2027@gmail.com",
  "extension": "718y8vl07u",
  "officeCode": "xmwtr523kr",
  "reportsTo": 3,
  "jobTitle": "manager"
}

### DELETE
DELETE  http://localhost:8000/employee/15 HTTP/1.1

### USER
### LOGIN
POST http://localhost:8000/user/login HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "12345689!"
}

### REGISTER
POST http://localhost:8000/user/register HTTP/1.1
content-type: application/json

{
  "username": "admin",
  "password": "12345689!",
  "employeeNumber": 14
}